# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the Allwinner device drivers.
#

obj-$(CONFIG_SUN4I_EMAC) += sun4i-emac.o
sunxi_gmac-objs := sunxi_gmac_ops.o sunxi-gmac.o
obj-$(CONFIG_SUNXI_GMAC) += sunxi_gmac.o
